include:
  - board: xiao_ble
    shield: totem_left
  - board: xiao_ble
    shield: totem_right
# there is no settingsreset (needed) for the XIAO
# But try it anyways ...
  - board: xiao_ble
    shield: settings_reset
